### ISSUE TITLE
Hi there mind if just grab some code here?

### ISSUE THREAD

**Issue by Zuruckt** [LucaswithC/Cat-Wiki#1]
So umh hi I've been wanting to do this challenge but can't stand writing css. 
I wonder if I could get the html and css layouts from you? I want to do this in Vue  and you would be fully credited.

thanks in advance

ps: I saw what you did in the read more def be keeping that if you agree

**Comment by lcas-k** [comment]
Hey, yeah sure, if you credit me you can grab what you need :)
